# WARNING
# Do not edit this file manually. Your changes will be overwritten with next FlowPDF update.
# WARNING

package FlowPDF::Constants;
use base qw/Exporter/;

use strict;
use warnings;
use constant {
    # Property in configuration where debug level is being stored.
    ## this property is being used for automatic debug level setup.
    DEBUG_LEVEL_PROPERTY                 => 'debugLevel',

    # Proxy related constants
    HTTP_PROXY_URL_PROPERTY              => 'httpProxyUrl',
    PROXY_CREDENTIAL_PROPERTY            => 'proxy_credential',

    # auth related constants
    AUTH_SCHEME_PROPERTY                 => 'authScheme',
    AUTH_SCHEME_VALUE_FOR_BASIC_AUTH     => 'basic',
    AUTH_SCHEME_VALUE_FOR_OAUTH_V1       => 'oauth',
    AUTH_SCHEME_VALUE_FOR_BEARER         => 'bearer',
    BASIC_AUTH_CREDENTIAL_PROPERTY       => 'basic_credential',

    # Certificate management related constants
    ## This property defines the property in configuration that defines certificates management policy.
    ## There are 3 policies total: 'strict', 'ignore', 'selfsigned'
    ## strict: all certificates that could not be verified by common CAs are wrong (default mode).
    ## ignore: all certificates are valid (btw, the only mode that cb-perl can operate).
    ## selfsigned: strict + exceptions from some location
    CM_POLICY_PROPERTY                   => 'cmPolicy',
    ## This property defines location type of self-signed certificates (or custom CAs).
    ## Technically custom CAs are not directly connected to self-signed certificates from technical point of view
    ## but handling mechanism is exactly the same. We need to have a file with certificate data to read it and
    ## validate certificate.
    ## Possible values are:
    ## 'property'
    ## 'filesystem'
    ## 'SDA-CertificateStorage' (this is not supported yet but we will have a placeholder for that).
    CM_SELFSIGNED_LOCATION_TYPE_PROPERTY => 'cmCertsLocationType',
    ## Actual location of self-signed certificates.
    CM_SELFSIGNED_LOCATION_PROPERTY      => 'cmCertsLocation',
    ## Certificate management policies:
    CM_POLICY_STRICT                     => 'strict',
    CM_POLICY_SELFSIGNED                 => 'selfsigned',
    CM_POLICY_IGNORE                     => 'ignore',
    ## Certificate management location types:
    CM_LOCATION_TYPE_PROPERTY            => 'property',
    CM_LOCATION_TYPE_FILESYSTEM          => 'filesystem',
    CM_LOCATION_TYPE_SDA_CERT_STORAGE    => 'sda-certificate-storage',
    # This is not supported yet, so it is not exposed.
    OAUTH_CREDENTIAL_PROPERTY            => 'oauth_credential',
};

our @EXPORT_OK = qw/
    DEBUG_LEVEL_PROPERTY
    HTTP_PROXY_URL_PROPERTY
    PROXY_CREDENTIAL_PROPERTY
    AUTH_SCHEME_PROPERTY
    AUTH_SCHEME_VALUE_FOR_BASIC_AUTH
    AUTH_SCHEME_VALUE_FOR_OAUTH_V1
    AUTH_SCHEME_VALUE_FOR_BEARER
    BASIC_AUTH_CREDENTIAL_PROPERTY
    CM_POLICY_PROPERTY
    CM_SELFSIGNED_LOCATION_TYPE_PROPERTY
    CM_SELFSIGNED_LOCATION_PROPERTY
    CM_POLICY_STRICT
    CM_POLICY_SELFSIGNED
    CM_POLICY_IGNORE
    CM_LOCATION_TYPE_PROPERTY
    CM_LOCATION_TYPE_FILESYSTEM
    CM_LOCATION_TYPE_SDA_CERT_STORAGE
/;

1;
