version: '3'
services:
  efserver:
    image: "electricflow/efserver:latest"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - external
    container_name: efserver
    hostname: "efserver"
    tty: true
networks:
  external:
    driver: bridge
